import './globals.css'
import Intro from "./_components/Intro";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {/****I can put things here that are always seen****/}



        {/********/}

        <main>{children}</main>
      </body>
    </html>
  )
}
