

import './globals.css'
import { DataProvider } from './_context/DataContext'
import { useContext } from 'react'
import DataContext from "./_context/DataContext";



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  // const { lightMode } = useContext(DataContext);

  return (
    <DataProvider>
      <html lang="en" className='overflow-hidden'>
        <body>
          <main>{children}</main>
        </body>
      </html>
    </DataProvider>
  )
}
