import './globals.css'
import { DataProvider } from './_context/DataContext'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <DataProvider>
      <html lang="en">
        <body>
          <main>{children}</main>
        </body>
      </html>
    </DataProvider>
  )
}
